name: recipe_ir
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  file_picker: ^5.2.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/demo/
